//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActivateSensorCore.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ActivateSensorCore.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MyDemo App.
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Later.
        /// </summary>
        internal static string LaterButton {
            get {
                return ResourceManager.GetString("LaterButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch on.
        /// </summary>
        internal static string LocationActivationButton {
            get {
                return ResourceManager.GetString("LocationActivationButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This application requires location data in order to work correctly.
        /// </summary>
        internal static string LocationActivationExplanation {
            get {
                return ResourceManager.GetString("LocationActivationExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch on location sensor.
        /// </summary>
        internal static string LocationActivationTitle {
            get {
                return ResourceManager.GetString("LocationActivationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch on.
        /// </summary>
        internal static string MotionDataActivationButton {
            get {
                return ResourceManager.GetString("MotionDataActivationButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This application requires motion data in order to work correctly.
        /// </summary>
        internal static string MotionDataActivationExplanation {
            get {
                return ResourceManager.GetString("MotionDataActivationExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch on motion data.
        /// </summary>
        internal static string MotionDataActivationTitle {
            get {
                return ResourceManager.GetString("MotionDataActivationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not ask again.
        /// </summary>
        internal static string NeverButton {
            get {
                return ResourceManager.GetString("NeverButton", resourceCulture);
            }
        }
    }
}
